services:
  db:
    image: postgres:15.2
    container_name: sa_project_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sa_project_app
    restart: unless-stopped
    volumes:
      - ./backend:/app/src/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
