# Generated by Django 5.0.7 on 2024-07-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('price_for_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('similar_details', models.ManyToManyField(blank=True, to='details.detail')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='PlannedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed_quantity', models.PositiveIntegerField(default=0)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.detail')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_details', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Planned Detail',
                'verbose_name_plural': 'Planned Details',
            },
        ),
        migrations.CreateModel(
            name='DetailInStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_in_stock', to='details.detail')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_in_stock', to='details.warehouse')),
            ],
            options={
                'verbose_name': 'Detail In Stock',
                'verbose_name_plural': 'Details In Stock',
            },
        ),
    ]
