# Generated by Django 5.0.7 on 2024-07-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailinstock',
            options={'ordering': ['id'], 'verbose_name': 'Detail In Stock', 'verbose_name_plural': 'Details In Stock'},
        ),
        migrations.AlterModelOptions(
            name='planneddetail',
            options={'ordering': ['id'], 'verbose_name': 'Planned Detail', 'verbose_name_plural': 'Planned Details'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
