# Generated by Django 5.0.7 on 2024-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_detailinstock_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planneddetail',
            old_name='planed_quantity',
            new_name='planned_quantity',
        ),
    ]
